name: Noak Public Website Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint
      
      - name: Build project
        run: npm run build
        
      - name: Upload Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.naufalfalah.com
          username: test-noak@naufalfalah.com
          password: _I=Qf6cIAVph
          local-dir: out/
          server-dir: /home/u1807002/public_html/noak.single-billing-event.com
          port: 21
          protocol: ftp
